stages:
  - test

py27:
  image: python:2.7
  stage: test
  script:
    - pip install tox
    - tox -e py27

py36:
  image: python:3.6
  stage: test
  script:
    - pip install tox
    - tox -e py36

flake8:
  image: python:3.6
  stage: test
  script:
    - pip install tox
    - tox -e flake8

docs:
  image: python:3.6
  stage: test
  script:
    - pip install sphinx
    - cd docs
    - sphinx-build -M singlehtml . _build
    - sphinx-build -M linkcheck  . _build | tee linkcheck.log
    - ! grep 'ok.*- unauthorized' linkcheck.log
