stages:
  - test

py27:
  image: python:2.7
  stage: test
  script:
    - tox -e py27

py36:
  image: python:3.6
  stage: test
  script:
    - tox -e py36

flake8:
  image: python:3.6
  stage: test
  script:
    - tox -e flake8
